FROM node:20-bookworm-slim AS base

FROM base AS deps
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY prisma prisma

RUN apt-get update -y && apt-get install -y openssl
RUN corepack enable
RUN yarn --immutable

CMD ["yarn", "prisma", "migrate", "deploy"]
